docs: add tutorial blob-url
google/shaka-player pull request #3401
Opened 2021-05-13 01:18 UTC by kocoten1992

## Description

Fixes: https://github.com/google/shaka-player/issues/1481

## Checklist:

- [ ] I have signed the Google CLA <https://cla.developers.google.com>
- [ ] My code follows the style guidelines of this project
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have verified my change on multiple browsers on different platforms
- [ ] I have run `./build/all.py` and the build passes
- [ ] I have run `./build/test.py` and all tests pass

2021-05-14 00:27 UTC, kocoten1992 commented
Hi @joeyparrish, this PR is ready for review

2021-05-14 17:29 UTC, joeyparrish requested changes
Thanks for contributing!

2021-05-14 17:29 UTC, joeyparrish commented on lib/net/http_fetch_plugin.js
> +  shaka.net.NetworkingEngine.registerScheme(
Can you please move this change to a separate PR?  That way, we can cherry-pick this PR to the older release branches to document the process for them, without importing this new feature.  Thanks!

2021-05-14 17:29 UTC, joeyparrish commented on docs/tutorials/blob-url.md
> +- Register blob scheme to network engine (note: you don't have to do this in v3.x)
This is not quite true.  You don't have to do it in v3.2+.

2021-05-14 17:29 UTC, joeyparrish commented on docs/tutorials/blob-url.md
> +  `player.load: player.load(uri, null, shaka.dash.DashParser);`
Not sure why you have `player.load: ` before the call.  Would you please remove it?

2021-05-14 17:29 UTC, joeyparrish commented on docs/tutorials/blob-url.md
> +  This can be worked around with either absolute URIs or the use of BaseURL element in DASH.
These comments about relative URIs are generally applicable to all versions of Shaka Player, and to HLS as well as DASH.  Would you please move them to a separate section at the top?

2021-05-14 17:29 UTC, joeyparrish commented on docs/tutorials/blob-url.md
> +#### For version v3.x (v3.2 and up)
I think you mean v3.1 and below, since you're adding this code to v3.2 already.

2021-08-19 08:27 UTC, denissabramovs commented
Why this is still not merged? This is pretty useful stuff. I was looking for a way to play blobs coming from websocket connection.

2021-08-19 11:54 UTC, theodab commented
> Why this is still not merged? This is pretty useful stuff. I was looking for a way to play blobs coming from websocket connection.

The author has not yet responded to Joey's change requests.

2021-08-19 17:47 UTC, kocoten1992 commented
thanks @avelad !

2021-08-19 17:47 UTC, closed without merging